#!/bin/bash

if [ $1 = "a" ]
then
    yt-dlp -x --audio-format mp3 $2
elif [ $1 = "v" ]
then
    video_id=$(yt-dlp -F $2 | sed -e '1,/-$/d' -e 's/ .*//g' | fzf --reverse --preview "yt-dlp -F '$2'")
    yt-dlp -f $video_id $2
elif [[ $1 = "a+v" || $1 = "v+a" ]]
then
    video_id=$(yt-dlp -F $2 | sed -e '1,/-$/d' -e 's/ .*//g' | fzf --reverse --preview "yt-dlp -F '$2'")
    audio_id=$(yt-dlp -F $2 | sed -e '1,/-$/d' -e 's/ .*//g' | fzf --reverse --preview "yt-dlp -F '$2'")
    yt-dlp -f $video_id+$audio_id $2
fi
